# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNo', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('cellNo', models.CharField(max_length=11)),
            ],
        ),
    ]
