# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='idNo',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
