# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leap', '0002_auto_20170510_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cellNo',
            field=models.CharField(max_length=11, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='idNo',
            field=models.CharField(max_length=8, unique=True, verbose_name='ID Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
    ]
