# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leap', '0003_auto_20170510_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeapClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classCode', models.CharField(max_length=4, unique=True, verbose_name='Class Code')),
                ('className', models.CharField(max_length=100, verbose_name='Class Name')),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='enrolledClass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leap.LeapClass'),
        ),
    ]
